spring:
  application:
    name: dabom
  server:
    address: 0.0.0.0

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        default_batch_fetch_size: 20
#        format_sql: true


  #  sql:
#    init:
#      mode: always
#      platform: mariadb
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql

  servlet:
    multipart:
      max-file-size: 100MB # 최대 파일 사이즈
      max-request-size: 100MB # 한 번 요청의 최대 사이즈

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: Naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            redirect-uri: ${NAVER_REDIRECT_URI}
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope: profile_nickname
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
        presigned-url-duration: ${S3_PRESIGNED_URL_DURATION}
        presigned-url-duration-img: ${S3_PRESIGNED_URL_IMG_DURATION}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ${S3_REGION}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

file:
  upload:
    path: ${FILE_PATH}
    url: ${FILE_URL}
  ffmpeg:
    path: ${FFMPEG_PATH}
    hls:
      segment-duration: ${FFMPEG_SEGMENT_DURATION}

websocket:
  allowed-origin: ${SERVER}

app:
  cookie:
    isSecure: ${COOKIE_SECURE:false}
    sameSite: ${COOKIE_SAME_SITE:Lax}
    domain: ${COOKIE_DOMAIN:localhost}